export default [
  {
    id: "0",
    title: "Development, Implementation, Operational of Mobile",
    Assigned: "Sagar",
    Created: "Soumya Ranjan",
    FormTitle: "Integrate CMS Page",
    Status: "In Progress",
    TaskPhase: "Developement",
    StartDate: "11/07/2023",
    time: "48",
    Qc: "YES",
    Priority: "Low",
    TaskType: "Custom Developement",
    TaskComplexity: "Medium",
  },
  {
    id: "1",
    title: "Testing, Deployment, Support of Web App",
    Assigned: "John Doe",
    Created: "Jane Smith",
    FormTitle: "Optimize Database Queries",
    Status: "Completed",
    TaskPhase: "Testing",
    StartDate: "05/15/2023",
    time: "32",
    Qc: "NO",
    Priority: "High",
    TaskType: "System Maintenance",
    TaskComplexity: "Low",
  },
  {
    id: "2",
    title: "UX/UI Design for E-commerce Platform",
    Assigned: "Alice Johnson",
    Created: "Bob Williams",
    FormTitle: "Design Landing Page",
    Status: "Pending",
    TaskPhase: "Design",
    StartDate: "09/22/2023",
    time: "24",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "User Interface Design",
    TaskComplexity: "High",
  },

  {
    id: "3",
    title: "Backend Development for CRM System",
    Assigned: "Eva Brown",
    Created: "Chris Miller",
    FormTitle: "Implement User Authentication",
    Status: "In Progress",
    TaskPhase: "Development",
    StartDate: "11/02/2023",
    time: "40",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "Backend Development",
    TaskComplexity: "High",
  },
  {
    id: "4",
    title: "Mobile App Prototype for Social Media",
    Assigned: "David Wilson",
    Created: "Emily Davis",
    FormTitle: "Create Home Screen Design",
    Status: "Pending",
    TaskPhase: "Design",
    StartDate: "08/10/2023",
    time: "18",
    Qc: "NO",
    Priority: "Low",
    TaskType: "Mobile App Design",
    TaskComplexity: "Medium",
  },
  {
    id: "5",
    title: "Frontend Development for Blog Website",
    Assigned: "Grace Taylor",
    Created: "Harry Johnson",
    FormTitle: "Implement Responsive Layout",
    Status: "In Progress",
    TaskPhase: "Development",
    StartDate: "10/15/2023",
    time: "36",
    Qc: "YES",
    Priority: "High",
    TaskType: "Frontend Development",
    TaskComplexity: "Medium",
  },
  {
    id: "6",
    title: "Quality Assurance for E-learning Platform",
    Assigned: "Oliver White",
    Created: "Sophia Martinez",
    FormTitle: "Conduct System Testing",
    Status: "Pending",
    TaskPhase: "Testing",
    StartDate: "09/05/2023",
    time: "28",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "Quality Assurance",
    TaskComplexity: "High",
  },
  {
    id: "7",
    title: "Testing, Deployment, Support of Web App",
    Assigned: "John Doe",
    Created: "Jane Smith",
    FormTitle: "Optimize Database Queries",
    Status: "Completed",
    TaskPhase: "Testing",
    StartDate: "05/15/2023",
    time: "32",
    Qc: "NO",
    Priority: "High",
    TaskType: "System Maintenance",
    TaskComplexity: "Low",
  },
  {
    id: "8",
    title: "UX/UI Design for E-commerce Platform",
    Assigned: "Alice Johnson",
    Created: "Bob Williams",
    FormTitle: "Design Landing Page",
    Status: "Pending",
    TaskPhase: "Design",
    StartDate: "09/22/2023",
    time: "24",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "User Interface Design",
    TaskComplexity: "High",
  },
  {
    id: "8",
    title: "UX/UI Design for E-commerce Platform",
    Assigned: "Alice Johnson",
    Created: "Bob Williams",
    FormTitle: "Design Landing Page",
    Status: "Pending",
    TaskPhase: "Design",
    StartDate: "09/22/2023",
    time: "24",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "User Interface Design",
    TaskComplexity: "High",
  },
  {
    id: "8",
    title: "UX/UI Design for E-commerce Platform",
    Assigned: "Alice Johnson",
    Created: "Bob Williams",
    FormTitle: "Design Landing Page",
    Status: "Pending",
    TaskPhase: "Design",
    StartDate: "09/22/2023",
    time: "24",
    Qc: "YES",
    Priority: "Medium",
    TaskType: "User Interface Design",
    TaskComplexity: "High",
  },
];
